import { Piece } from '@/types'
import {
  whiteBishopMovementRange,
  whitePawnInitialMovementRange,
  whiteKingMovementRange,
  whiteKnightMovementRange,
  whitePawnMovementRange,
  whiteQueenMovementRange,
  whiteRookMovementRange,
  whitePawnAttackRange,
  blackPawnMovementRange,
  blackPawnInitialMovementRange,
  blackPawnAttackRange,
  blackRookMovementRange,
  blackKnightMovementRange,
  blackBishopMovementRange,
  blackKingMovementRange,
  blackQueenMovementRange,
} from './movementRanges'

export function generateInitialPieceState(): Piece[] {
  return [
    {
      id: `white-rook-1`,
      name: `rook`,
      position: [1, 8],
      movementRange: whiteRookMovementRange,
      initialMovementRange: whiteRookMovementRange,
      attackRange: whiteRookMovementRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-knight-1`,
      name: `knight`,
      position: [2, 8],
      movementRange: whiteKnightMovementRange,
      initialMovementRange: whiteKnightMovementRange,
      attackRange: whiteKnightMovementRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-bishop-1`,
      name: `bishop`,
      position: [3, 8],
      movementRange: whiteBishopMovementRange,
      initialMovementRange: whiteBishopMovementRange,
      attackRange: whiteBishopMovementRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-king-1`,
      name: `king`,
      position: [4, 8],
      movementRange: whiteKingMovementRange,
      initialMovementRange: whiteKingMovementRange,
      attackRange: whiteKingMovementRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-queen-1`,
      name: `queen`,
      position: [5, 8],
      movementRange: whiteQueenMovementRange,
      initialMovementRange: whiteQueenMovementRange,
      attackRange: whiteQueenMovementRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-bishop-2`,
      name: `bishop`,
      position: [6, 8],
      movementRange: whiteBishopMovementRange,
      initialMovementRange: whiteBishopMovementRange,
      attackRange: whiteBishopMovementRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-knight-2`,
      name: `knight`,
      position: [7, 8],
      movementRange: whiteKnightMovementRange,
      initialMovementRange: whiteKnightMovementRange,
      attackRange: whiteKnightMovementRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-rook-2`,
      name: `rook`,
      position: [8, 8],
      movementRange: whiteRookMovementRange,
      initialMovementRange: whiteRookMovementRange,
      attackRange: whiteRookMovementRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-pawn-1`,
      name: `pawn`,
      position: [1, 7],
      movementRange: whitePawnMovementRange,
      initialMovementRange: whitePawnInitialMovementRange,
      attackRange: whitePawnAttackRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-pawn-2`,
      name: `pawn`,
      position: [2, 7],
      movementRange: whitePawnMovementRange,
      initialMovementRange: whitePawnInitialMovementRange,
      attackRange: whitePawnAttackRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-pawn-3`,
      name: `pawn`,
      position: [3, 7],
      movementRange: whitePawnMovementRange,
      initialMovementRange: whitePawnInitialMovementRange,
      attackRange: whitePawnAttackRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-pawn-4`,
      name: `pawn`,
      position: [4, 7],
      movementRange: whitePawnMovementRange,
      initialMovementRange: whitePawnInitialMovementRange,
      attackRange: whitePawnAttackRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-pawn-5`,
      name: `pawn`,
      position: [5, 7],
      movementRange: whitePawnMovementRange,
      initialMovementRange: whitePawnInitialMovementRange,
      attackRange: whitePawnAttackRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-pawn-6`,
      name: `pawn`,
      position: [6, 7],
      movementRange: whitePawnMovementRange,
      initialMovementRange: whitePawnInitialMovementRange,
      attackRange: whitePawnAttackRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-pawn-7`,
      name: `pawn`,
      position: [7, 7],
      movementRange: whitePawnMovementRange,
      initialMovementRange: whitePawnInitialMovementRange,
      attackRange: whitePawnAttackRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `white-pawn-8`,
      name: `pawn`,
      position: [8, 7],
      movementRange: whitePawnMovementRange,
      initialMovementRange: whitePawnInitialMovementRange,
      attackRange: whitePawnAttackRange,
      player: `white`,
      status: `init`,
    },
    {
      id: `black-pawn-1`,
      name: `pawn`,
      position: [1, 2],
      movementRange: blackPawnMovementRange,
      initialMovementRange: blackPawnInitialMovementRange,
      attackRange: blackPawnAttackRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-pawn-2`,
      name: `pawn`,
      position: [2, 2],
      movementRange: blackPawnMovementRange,
      initialMovementRange: blackPawnInitialMovementRange,
      attackRange: blackPawnAttackRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-pawn-3`,
      name: `pawn`,
      position: [3, 2],
      movementRange: blackPawnMovementRange,
      initialMovementRange: blackPawnInitialMovementRange,
      attackRange: blackPawnAttackRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-pawn-4`,
      name: `pawn`,
      position: [4, 2],
      movementRange: blackPawnMovementRange,
      initialMovementRange: blackPawnInitialMovementRange,
      attackRange: blackPawnAttackRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-pawn-5`,
      name: `pawn`,
      position: [5, 2],
      movementRange: blackPawnMovementRange,
      initialMovementRange: blackPawnInitialMovementRange,
      attackRange: blackPawnAttackRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-pawn-6`,
      name: `pawn`,
      position: [6, 2],
      movementRange: blackPawnMovementRange,
      initialMovementRange: blackPawnInitialMovementRange,
      attackRange: blackPawnAttackRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-pawn-7`,
      name: `pawn`,
      position: [7, 2],
      movementRange: blackPawnMovementRange,
      initialMovementRange: blackPawnInitialMovementRange,
      attackRange: blackPawnAttackRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-pawn-8`,
      name: `pawn`,
      position: [8, 2],
      movementRange: blackPawnMovementRange,
      initialMovementRange: blackPawnInitialMovementRange,
      attackRange: blackPawnAttackRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-rook-1`,
      name: `rook`,
      position: [1, 1],
      movementRange: blackRookMovementRange,
      initialMovementRange: blackRookMovementRange,
      attackRange: blackRookMovementRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-knight-1`,
      name: `knight`,
      position: [2, 1],
      movementRange: blackKnightMovementRange,
      initialMovementRange: blackKnightMovementRange,
      attackRange: blackKnightMovementRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-bishop-1`,
      name: `bishop`,
      position: [3, 1],
      movementRange: blackBishopMovementRange,
      initialMovementRange: blackBishopMovementRange,
      attackRange: blackBishopMovementRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-king-1`,
      name: `king`,
      position: [4, 1],
      movementRange: blackKingMovementRange,
      initialMovementRange: blackKingMovementRange,
      attackRange: blackKingMovementRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-queen-1`,
      name: `queen`,
      position: [5, 1],
      movementRange: blackQueenMovementRange,
      initialMovementRange: blackQueenMovementRange,
      attackRange: blackQueenMovementRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-bishop-2`,
      name: `bishop`,
      position: [6, 1],
      movementRange: blackBishopMovementRange,
      initialMovementRange: blackBishopMovementRange,
      attackRange: blackBishopMovementRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-knight-2`,
      name: `knight`,
      position: [7, 1],
      movementRange: blackKnightMovementRange,
      initialMovementRange: blackKnightMovementRange,
      attackRange: blackKnightMovementRange,
      player: `black`,
      status: `init`,
    },
    {
      id: `black-rook-2`,
      name: `rook`,
      position: [8, 1],
      movementRange: blackRookMovementRange,
      initialMovementRange: blackRookMovementRange,
      attackRange: blackRookMovementRange,
      player: `black`,
      status: `init`,
    },
  ]
}

export const piecesInitialState = [
  {
    id: `white-rook-1`,
    name: `rook`,
    position: [1, 8],
    movementRange: whiteRookMovementRange,
    initialMovementRange: whiteRookMovementRange,
    attackRange: whiteRookMovementRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-knight-1`,
    name: `knight`,
    position: [2, 8],
    movementRange: whiteKnightMovementRange,
    initialMovementRange: whiteKnightMovementRange,
    attackRange: whiteKnightMovementRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-bishop-1`,
    name: `bishop`,
    position: [3, 8],
    movementRange: whiteBishopMovementRange,
    initialMovementRange: whiteBishopMovementRange,
    attackRange: whiteBishopMovementRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-king-1`,
    name: `king`,
    position: [4, 8],
    movementRange: whiteKingMovementRange,
    initialMovementRange: whiteKingMovementRange,
    attackRange: whiteKingMovementRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-queen-1`,
    name: `queen`,
    position: [5, 8],
    movementRange: whiteQueenMovementRange,
    initialMovementRange: whiteQueenMovementRange,
    attackRange: whiteQueenMovementRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-bishop-2`,
    name: `bishop`,
    position: [6, 8],
    movementRange: whiteBishopMovementRange,
    initialMovementRange: whiteBishopMovementRange,
    attackRange: whiteBishopMovementRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-knight-2`,
    name: `knight`,
    position: [7, 8],
    movementRange: whiteKnightMovementRange,
    initialMovementRange: whiteKnightMovementRange,
    attackRange: whiteKnightMovementRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-rook-2`,
    name: `rook`,
    position: [8, 8],
    movementRange: whiteRookMovementRange,
    initialMovementRange: whiteRookMovementRange,
    attackRange: whiteRookMovementRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-pawn-1`,
    name: `pawn`,
    position: [1, 7],
    movementRange: whitePawnMovementRange,
    initialMovementRange: whitePawnInitialMovementRange,
    attackRange: whitePawnAttackRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-pawn-2`,
    name: `pawn`,
    position: [2, 7],
    movementRange: whitePawnMovementRange,
    initialMovementRange: whitePawnInitialMovementRange,
    attackRange: whitePawnAttackRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-pawn-3`,
    name: `pawn`,
    position: [3, 7],
    movementRange: whitePawnMovementRange,
    initialMovementRange: whitePawnInitialMovementRange,
    attackRange: whitePawnAttackRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-pawn-4`,
    name: `pawn`,
    position: [4, 7],
    movementRange: whitePawnMovementRange,
    initialMovementRange: whitePawnInitialMovementRange,
    attackRange: whitePawnAttackRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-pawn-5`,
    name: `pawn`,
    position: [5, 7],
    movementRange: whitePawnMovementRange,
    initialMovementRange: whitePawnInitialMovementRange,
    attackRange: whitePawnAttackRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-pawn-6`,
    name: `pawn`,
    position: [6, 7],
    movementRange: whitePawnMovementRange,
    initialMovementRange: whitePawnInitialMovementRange,
    attackRange: whitePawnAttackRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-pawn-7`,
    name: `pawn`,
    position: [7, 7],
    movementRange: whitePawnMovementRange,
    initialMovementRange: whitePawnInitialMovementRange,
    attackRange: whitePawnAttackRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `white-pawn-8`,
    name: `pawn`,
    position: [8, 7],
    movementRange: whitePawnMovementRange,
    initialMovementRange: whitePawnInitialMovementRange,
    attackRange: whitePawnAttackRange,
    player: `white`,
    status: `init`,
  },
  {
    id: `black-pawn-1`,
    name: `pawn`,
    position: [1, 2],
    movementRange: blackPawnMovementRange,
    initialMovementRange: blackPawnInitialMovementRange,
    attackRange: blackPawnAttackRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-pawn-2`,
    name: `pawn`,
    position: [2, 2],
    movementRange: blackPawnMovementRange,
    initialMovementRange: blackPawnInitialMovementRange,
    attackRange: blackPawnAttackRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-pawn-3`,
    name: `pawn`,
    position: [3, 2],
    movementRange: blackPawnMovementRange,
    initialMovementRange: blackPawnInitialMovementRange,
    attackRange: blackPawnAttackRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-pawn-4`,
    name: `pawn`,
    position: [4, 2],
    movementRange: blackPawnMovementRange,
    initialMovementRange: blackPawnInitialMovementRange,
    attackRange: blackPawnAttackRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-pawn-5`,
    name: `pawn`,
    position: [5, 2],
    movementRange: blackPawnMovementRange,
    initialMovementRange: blackPawnInitialMovementRange,
    attackRange: blackPawnAttackRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-pawn-6`,
    name: `pawn`,
    position: [6, 2],
    movementRange: blackPawnMovementRange,
    initialMovementRange: blackPawnInitialMovementRange,
    attackRange: blackPawnAttackRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-pawn-7`,
    name: `pawn`,
    position: [7, 2],
    movementRange: blackPawnMovementRange,
    initialMovementRange: blackPawnInitialMovementRange,
    attackRange: blackPawnAttackRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-pawn-8`,
    name: `pawn`,
    position: [8, 2],
    movementRange: blackPawnMovementRange,
    initialMovementRange: blackPawnInitialMovementRange,
    attackRange: blackPawnAttackRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-rook-1`,
    name: `rook`,
    position: [1, 1],
    movementRange: blackRookMovementRange,
    initialMovementRange: blackRookMovementRange,
    attackRange: blackRookMovementRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-knight-1`,
    name: `knight`,
    position: [2, 1],
    movementRange: blackKnightMovementRange,
    initialMovementRange: blackKnightMovementRange,
    attackRange: blackKnightMovementRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-bishop-1`,
    name: `bishop`,
    position: [3, 1],
    movementRange: blackBishopMovementRange,
    initialMovementRange: blackBishopMovementRange,
    attackRange: blackBishopMovementRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-king-1`,
    name: `king`,
    position: [4, 1],
    movementRange: blackKingMovementRange,
    initialMovementRange: blackKingMovementRange,
    attackRange: blackKingMovementRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-queen-1`,
    name: `queen`,
    position: [5, 1],
    movementRange: blackQueenMovementRange,
    initialMovementRange: blackQueenMovementRange,
    attackRange: blackQueenMovementRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-bishop-2`,
    name: `bishop`,
    position: [6, 1],
    movementRange: blackBishopMovementRange,
    initialMovementRange: blackBishopMovementRange,
    attackRange: blackBishopMovementRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-knight-2`,
    name: `knight`,
    position: [7, 1],
    movementRange: blackKnightMovementRange,
    initialMovementRange: blackKnightMovementRange,
    attackRange: blackKnightMovementRange,
    player: `black`,
    status: `init`,
  },
  {
    id: `black-rook-2`,
    name: `rook`,
    position: [8, 1],
    movementRange: blackRookMovementRange,
    initialMovementRange: blackRookMovementRange,
    attackRange: blackRookMovementRange,
    player: `black`,
    status: `init`,
  },
] as Piece[]
